services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: on-failure
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5

  http_server:
    build: ./m1
    container_name: http_server
    restart: on-failure
    ports:
      - 8080:3000
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      RABBITMQ: rabbitmq
      PORT: 3000
      TASK_QUEUE: tasks
      RESPONSE_QUEUE: results

  worker:
    build: ./m2
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      RABBITMQ: rabbitmq
      TASK_QUEUE: tasks
      RESPONSE_QUEUE: results

volumes:
  rabbitmq:
